.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CONTRAIL\-SVC\-MONITOR" "1" "September 2015" "" ""
.
.SH "NAME"
\fBcontrail\-svc\-monitor\fR \- OpenContrail API
.
.SH "SYNOPSIS"
\fBcontrail\-svc\-monitor\fR [\fIoptions\fR]
.
.SH "DESCRIPTION"
Contrail svc monitor
.
.SH "OPTIONS"
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show this help message and exit
.
.TP
\fB\-c\fR \fIFILE\fR, \fB\-\-conf_file\fR \fIFILE\fR
Specify config file
.
.SH "BUGS"
Contrail is hosted in Launchpad so you can view current bugs at https://bugs\.launchpad\.net/opencontrail/\.
.
.SH "AUTHOR"
OpenContrail developers \fIdev@lists\.opencontrail\.org\fR
.
.SH "COPYRIGHT"
Copyright (c) 2014 OpenContrail
.
.SH "SEE ALSO"
contrail\-schema(1), contrail\-discovery(1), contrail\-api(1)
