.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "VRFSTATS" "1" "September 2015" "" ""
.
.SH "NAME"
\fBvrfstats\fR \- OpenContrail vRouter utils
.
.SH "SYNOPSIS"
\fBvrfstats\fR [\fIoptions\fR]
.
.SH "DESCRIPTION"
The OpenContrail vRouter is a forwarding plane (of a distributed router) that runs in the hypervisor of a virtualized server\.
.
.P
The package opencontrail\-vrouter\-utils provides command line utilities to configure and diagnose the OpenContrail linux kernel module\.
.
.SH "OPTIONS"
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show this help message and exit
.
.TP
\fB\-\-dump\fR
Displays packet statistics for all vrfs
.
.TP
\fB\-\-get\fR \fIvrf\fR
Displays packet statistics for the vrf \fIvrf\fR
.
.SH "BUGS"
Contrail is hosted in Launchpad so you can view current bugs at https://bugs\.launchpad\.net/opencontrail/\.
.
.SH "AUTHOR"
OpenContrail developers \fIdev@lists\.opencontrail\.org\fR
.
.SH "COPYRIGHT"
Copyright (c) 2014 OpenContrail
.
.SH "SEE ALSO"
mpls(1), dropstats(1), flow(1), vrfstats(1), nh(1), vif(1), vxlan(1), mirror(1), rt(1)
